apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-couchbase
  labels:
    {{- include "pcc.componentLabels" (merge (dict "component" "couchbase") .) | nindent 4 }}
type: Opaque
stringData:
  COUCHBASE_USERNAME: {{ .Values.couchbase.username | quote }}
  COUCHBASE_PASSWORD: {{ .Values.couchbase.password | quote }}
